global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'dev-app'
    metrics_path: /metrics
    static_configs:
      - targets: ['dev-app:80']

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['localhost:9100']

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['localhost:8081']
